language: php

php:
  - 5.4

before_script:
  - sudo apt-get install nodejs
  - wget https://github.com/n1k0/casperjs/archive/1.1-beta3.tar.gz -O /tmp/casper.tar.gz
  - tar -xvf /tmp/casper.tar.gz
  - export PATH=$PATH:$PWD/casperjs-1.1-beta3/bin/
  - phantomjs --version
  - casperjs --version
  - nohup php -S localhost:8080 > /dev/null 2>&1 &
  - sleep 3

script:
  - cd test
  - casperjs test assignment-*-*.js --server=http://localhost:8080
